// Base de datos de premios: 100 números asociados con 100 premios
const premios = [
    { numero: 1, premio: "Premio 1 Pack de fotografia" },
    { numero: 2, premio: "Premio 5 Tarjetas Reparacion gratuita Paleto Exotis" },
    { numero: 3, premio: "Premio 5 Tarjetas Reparacion gratuita Paleto Exotis" },
    { numero: 4, premio: "Premio Prismaticos" },
    { numero: 5, premio: "Premio 5% descuento en un tuneo en Paleto Exotics" },
    { numero: 6, premio: "Premio Pack 3 y 3 de comida y bebida" },
    { numero: 7, premio: "Premio Pack de 5 de pintura y 5 disolventes" },
    { numero: 8, premio: "Premio 5000$" },
    { numero: 9, premio: "Premio 5 Tarjetas Reparacion gratuita Paleto Exotis" },
    { numero: 10, premio: "Premio Pack 3 y 3 de comida y bebida" },
    { numero: 11, premio: "Premio Pack de 5 de pintura y 5 disolventes" },
    { numero: 12, premio: "Premio 5 sobres de TCG" },
    { numero: 13, premio: "Premio 5 sobres de TCG" },
    { numero: 14, premio: "Premio 5000$" },
    { numero: 15, premio: "Premio Skate" },
    { numero: 16, premio: "Premio 1 Pack de fotografia" },
    { numero: 17, premio: "Premio 5 Tarjetas Reparacion gratuita Paleto Exotis" },
    { numero: 18, premio: "Premio Pack de 5 de pintura y 5 disolventes" },
    { numero: 19, premio: "Premio 5 Tarjetas Reparacion gratuita Paleto Exotis" },
    { numero: 20, premio: "Premio Pack 3 y 3 de comida y bebida" },
    { numero: 21, premio: "Premio 5 sobres de TCG" },
    { numero: 22, premio: "Premio Skate" },
    { numero: 23, premio: "Premio Pack de 5 de pintura y 5 disolventes" },
    { numero: 24, premio: "Premio 1000$" },
    { numero: 25, premio: "Premio 1000$" },
    { numero: 26, premio: "Premio 1 Pack de fotografia" },
    { numero: 27, premio: "Premio 1000$" },
    { numero: 28, premio: "Premio Pack de 5 de pintura y 5 disolventes" },
    { numero: 29, premio: "Premio 25 cebos" },
    { numero: 30, premio: "Premio Pack de 5 de pintura y 5 disolventes" },
    { numero: 31, premio: "Premio Prismaticos" },
    { numero: 32, premio: "Premio 5 Tarjetas Reparacion gratuita Paleto Exotis" },
    { numero: 33, premio: "Premio 5000$" },
    { numero: 34, premio: "Premio Prismaticos" },
    { numero: 35, premio: "Premio 5 sobres de TCG" },
    { numero: 36, premio: "Premio 5 Tarjetas Reparacion gratuita Paleto Exotis" },
    { numero: 37, premio: "Premio 1 Pack de fotografia" },
    { numero: 38, premio: "Premio 5 sobres de TCG" },
    { numero: 39, premio: "Premio Skate" },
    { numero: 40, premio: "Premio 5 kits de limpieza" },
    { numero: 41, premio: "Premio Skate" },
    { numero: 42, premio: "Premio 25 cebos" },
    { numero: 43, premio: "Premio Pack de 5 de pintura y 5 disolventes" },
    { numero: 44, premio: "Premio 5% descuento en un tuneo en Paleto Exotics" },
    { numero: 45, premio: "Premio 5 Tarjetas Reparacion gratuita Paleto Exotis" },
    { numero: 46, premio: "Premio 25 cebos" },
    { numero: 47, premio: "Premio 5 kits de limpieza" },
    { numero: 48, premio: "Premio 5 sobres de TCG" },
    { numero: 49, premio: "Premio 5 kits de limpieza" },
    { numero: 50, premio: "Premio Pack 3 y 3 de comida y bebida" },
    { numero: 51, premio: "Premio 5 Tarjetas Reparacion gratuita Paleto Exotis" },
    { numero: 52, premio: "Premio 5 kits de limpieza" },
    { numero: 53, premio: "Premio Pack de 5 de pintura y 5 disolventes" },
    { numero: 54, premio: "Premio 5 sobres de TCG" },
    { numero: 55, premio: "Premio Altavoz" },
    { numero: 56, premio: "Premio 5 kits de limpieza" },
    { numero: 57, premio: "Premio Pack 3 y 3 de comida y bebida" },
    { numero: 58, premio: "Premio Skate" },
    { numero: 59, premio: "Premio 5 kits de limpieza" },
    { numero: 60, premio: "Premio 5 Tarjetas Reparacion gratuita Paleto Exotis" },
    { numero: 61, premio: "Premio 50 cebos" },
    { numero: 62, premio: "Premio Altavoz" },
    { numero: 63, premio: "Premio Pack de 5 de pintura y 5 disolventes" },
    { numero: 64, premio: "Premio Skate" },
    { numero: 65, premio: "Premio 5 kits de limpieza" },
    { numero: 66, premio: "Premio 1 Pack de fotografia" },
    { numero: 67, premio: "Premio Altavoz" },
    { numero: 68, premio: "Premio 5 kits de limpieza" },
    { numero: 69, premio: "Premio Prismaticos" },
    { numero: 70, premio: "Premio 5% descuento en un tuneo en Paleto Exotics" },
    { numero: 71, premio: "Premio 5 sobres de TCG" },
    { numero: 72, premio: "Premio Pack de 5 de pintura y 5 disolventes" },
    { numero: 73, premio: "Premio Pack 3 y 3 de comida y bebida" },
    { numero: 74, premio: "Premio 5 kits de limpieza" },
    { numero: 75, premio: "Premio 5 sobres de TCG" },
    { numero: 76, premio: "Premio 5 kits de limpieza " },
    { numero: 77, premio: "Premio Altavoz" },
    { numero: 78, premio: "Premio 5% descuento en un tuneo en Paleto Exotics" },
    { numero: 79, premio: "Premio Altavoz" },
    { numero: 80, premio: "Premio Pack 3 y 3 de comida y bebida" },
    { numero: 81, premio: "Premio Patines" },
    { numero: 82, premio: "Premio Patines" },
    { numero: 83, premio: "Premio Prismaticos" },
    { numero: 84, premio: "Premio Altavoz" },
    { numero: 85, premio: "Premio Patines" },
    { numero: 86, premio: "Premio Pack 3 y 3 de comida y bebida" },
    { numero: 87, premio: "Premio Patines" },
    { numero: 88, premio: "Premio 5% descuento en un tuneo en Paleto Exotics" },
    { numero: 89, premio: "Premio Altavoz" },
    { numero: 90, premio: "Premio 5 sobres de TCG" },
    { numero: 91, premio: "Premio Pack 3 y 3 de comida y bebida" },
    { numero: 92, premio: "Premio Altavoz" },
    { numero: 93, premio: "Premio Skate" },
    { numero: 94, premio: "Premio Patines" },
    { numero: 95, premio: "Premio 50 cebos" },
    { numero: 96, premio: "Premio Skate" },
    { numero: 97, premio: "Premio Patines" },
    { numero: 98, premio: "Premio Pack 3 y 3 de comida y bebida" },
    { numero: 99, premio: "Premio Patines" },
    { numero: 100, premio: "Premio Patines" }
];

// Función para buscar el premio asociado
function buscarPremio() {
    const numeroInput = document.getElementById("numero").value; // Obtiene el número ingresado
    const numero = parseInt(numeroInput); // Convierte a número
    const resultado = premios.find(item => item.numero === numero); // Busca el premio

    // Muestra el resultado
    const resultadoDiv = document.getElementById("resultado");
    if (resultado) {
        resultadoDiv.innerHTML = `El premio asociado al número ${numero} es: <strong>${resultado.premio}</strong>`;
    } else {
        resultadoDiv.innerHTML = `No hay premio asociado al número ${numero}.`;
    }
}
